### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by skyflysun** [disjfa/vuetify-sidebar-template#2]
readme文件没讲如何运行，grunt也找不到默认任务

**Comment by disjfa** [comment]
I only use grunt for the main project, and that piece does not do anything in the project.

I think you cloned my project instead of:  
``` 
vue init disjfa/vuetify-sidebar-template my-project
```
google translated:
我只为主项目使用grunt，而这个项目在项目中没有做任何事情。

我想你克隆我的项目，而不是：^^

**Comment by disjfa** [comment]
The template itself uses webpack, not grunt.
模板本身使用webpack，而不是咕噜咕噜。
